set(_CATKIN_CURRENT_PACKAGE "tutorials")
set(tutorials_VERSION "0.0.0")
set(tutorials_MAINTAINER "Yang Seon-Je <sj.yang@skku.edu>")
set(tutorials_PACKAGE_FORMAT "2")
set(tutorials_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation")
set(tutorials_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(tutorials_BUILDTOOL_DEPENDS "catkin")
set(tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(tutorials_EXEC_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(tutorials_RUN_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(tutorials_TEST_DEPENDS )
set(tutorials_DOC_DEPENDS )
set(tutorials_DEPRECATED "")